#!/bin/sh

#
# get - tiny system info
#

OS=$(cat /etc/*-release | grep ^NAME= | cut -d '"' -f 2)
PACKAGES=$(pacman -Q | wc -l)

bc=$(tput bold)     # bold
c6=$(tput setaf 6)  # cyan
c7=$(tput setaf 7)  # white
rc=$(tput sgr0)     # reset

lc=${bc}${c6}       # labels
tc=${bc}${c7}       # text

cat <<EOF

${lc}OS:${rc}       ${tc}${OS}${rc}
${lc}PACKAGES:${rc} ${tc}${PACKAGES}${rc}
EOF
